---
title: 'STA-141A Fall 2022: Final Project'
author: 'Christina Li, Sydney Lee, Camden Possinger'
date: "`r Sys.Date()`"
output: 
  rmdformats::downcute:
    style_switcher: false
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  out.width = "100%",
  out.height = "100%",
  message = FALSE,
  warning = FALSE
)
```

# Introduction 

# Research Question

# Data Description

```{r}
library(readr)
library(purrr)
library(ggplot2)
library(broom)
library(skimr)
library(knitr)
library(car)
library(tidyr)
library(stringr)
library(plotly)
library(jtools)
library(broom)
library(dplyr)
library(kableExtra)
library(ggfortify)
library(fastDummies)
library(DT)


spotify_preprocess <- function() {
  df <- c(
    "60s",
    "70s",
    "80s",
    "90s",
    "00s",
    "10s"
  ) %>%
    purrr::set_names() %>%
    map(~ read_csv(paste0("dataset-of-", .x, ".csv"),
      show_col_types = FALSE
    )) %>%
    bind_rows(.id = "decade") %>%
    dplyr::select(
      -uri,
      -artist,
      -track,
      -instrumentalness,
      -loudness,
      -speechiness,
      -acousticness
    ) %>%
    group_by(decade) %>%
    group_split() %>%
    map(~
      .x %>%
        mutate(across(
          where(is.numeric),
          ~ ifelse(
            abs(as.numeric(scale(.x))) > 3,
            NA,
            .x
          )
        )) %>%
        na.omit()) %>%
    bind_rows() %>%
    dummy_cols(
      select_columns = c("key", "time_signature", "mode"),
      remove_selected_columns = TRUE,
      remove_first_dummy = TRUE
    ) %>%
    mutate(
      decade = factor(decade,
        levels = c(
          "60s",
          "70s",
          "80s",
          "90s",
          "00s",
          "10s"
        )
      ),
      danceability = exp(danceability),
      energy = exp(energy),
      valence = exp(valence),
      chorus_hit = log(chorus_hit),
      liveness = log(liveness),
      sections = log(sections),
      duration_ms = log(duration_ms),
      target = as.integer(target)
    )

  df[which(!is.infinite(rowSums(df %>% dplyr::select(where(is.numeric))))), ] %>% group_by(decade)
}
```

# Data Visualization 

## Summary Statistics

```{r}
spotify_preprocess() %>%
  filter(target == 1) %>%
  dplyr::select(where(is.double)) %>%
  skim() %>%
  focus(
    decade,
    numeric.mean,
    numeric.sd,
    numeric.hist
  ) %>%
  dplyr::select(-skim_type) %>%
  setNames(c("Covariate", "Decade", "Mean", "SD", "Hist")) %>%
  mutate(
    Mean = round(Mean, digits = 2),
    SD = round(SD, digits = 2)
  ) %>%
  datatable(
    extensions = "RowGroup",
    options = list(rowGroup = list(
      dataSrc = 1,
      startRender = JS(
        "function(rows, group) {",
        "  var style ='background-color:  #013220;'",
        "  var td = `<td style='${style}' colspan=12>${group}</td>`;",
        "  return $(`<tr>${td}</tr>`);",
        "}"
      )
    ))
  ) %>%
  formatRound(columns = 2:4, digits = 2)
  ```

## Continous Covariates

```{r}
ggplotly(
  spotify_preprocess() %>%
    filter(target == 1) %>%
    summarise(across(where(is.double), list(mean))) %>%
    pivot_longer(!decade, names_to = "feature", values_to = "mean") %>%
    mutate(feature = feature %>% str_remove("_1")) %>%
    ggplot(aes(x = mean, y = decade, fill = decade)) +
    geom_bar(stat = "identity") +
    ylab("Decade") +
    xlab("Mean") +
    labs(fill = "Decade") +
    facet_wrap(~feature, scales = "free_x"),
  height = 1000
) %>%
  config(displayModeBar = FALSE)
```

```{r}
ggplotly(
  spotify_preprocess() %>%
    filter(target == 1) %>%
    summarise(across(where(is.double), list(sd))) %>%
    pivot_longer(!decade, names_to = "feature", values_to = "sd") %>%
    mutate(feature = feature %>% str_remove("_1")) %>%
    ggplot(aes(x = sd, y = decade, fill = decade)) +
    geom_bar(stat = "identity") +
    ylab("Decade") +
    xlab("SD") +
    labs(fill = "Decade") +
    facet_wrap(~feature, scales = "free_x"),
  height = 1000
) %>%
  config(displayModeBar = FALSE)
```


```{r}
ggplotly(
  spotify_preprocess() %>%
    filter(target == 1) %>%
    dplyr::select(where(is.double)) %>%
    pivot_longer(!decade, names_to = "feature") %>%
    ggplot(aes(value, color = decade, fill = decade)) +
    geom_density(alpha = 0.2) +
    ylab("Density") +
    xlab("Value") +
    labs(fill = "Decade") +
    facet_wrap(~feature, scales = "free"),
  height = 1000
) %>%
  config(displayModeBar = FALSE)
```

## Discrete Covariates

```{r}
ggplotly(
  spotify_preprocess() %>%
    filter(target == 1) %>%
    dplyr::select(where(is.integer), -target) %>%
    pivot_longer(!decade, names_to = "feature") %>%
    filter(value == 1) %>%
    mutate(value = as.integer(value)) %>%
    group_by(decade, feature) %>%
    summarise(sum = sum(value)) %>%
    ggplot(aes(x = sum, y = decade, color = decade, fill = decade)) +
    geom_bar(stat = "identity") +
    ylab("Decade") +
    xlab("Count") +
    labs(fill = "Decade") +
    facet_wrap(~feature, scales = "free"),
  height = 1000
) %>%
  config(displayModeBar = FALSE)
```

# Methodology

# Results

```{r}
create_full_model <- function(df) {
  glm(target ~ ., family = binomial(link = "logit"), data = df)
}

create_reduced_model <- function(df, coef) {
  form <- paste0("target ~ ", paste0(coef, collapse = "+")) %>% as.formula()
  glm(form, family = binomial(link = "logit"), data = df)
}

full_model <- spotify_preprocess() %>%
  nest() %>%
  mutate(
    model = map(data, create_full_model),
    summary = map(model, ~ .x %>%
      tidy(exponentiate = TRUE) %>%
      na.omit()),
    glance = map(model, glance),
    sig_coef = map(summary, ~ .x %>%
      filter(p.value <= 0.05, term != "(Intercept)") %>%
      pull(term)),
    reduced_model = map2(data, sig_coef, create_reduced_model)
  )

reduced_model <- full_model %>%
  dplyr::select(decade, data, model = reduced_model) %>%
  mutate(
    summary = map(model, ~ .x %>% tidy(exponentiate = TRUE)),
    vif = map(model, vif),
    glance = map(model, glance),
    sig_coef = map(summary, ~ .x %>%
      filter(p.value <= 0.05, term != "(Intercept)") %>%
      pull(term)),
    reduced_model = map2(data, sig_coef, create_reduced_model)
  )

reduced_model <- reduced_model %>%
  dplyr::select(decade, data, model = reduced_model) %>%
  mutate(
    summary = map(model, ~ .x %>% tidy(exponentiate = TRUE)),
    vif = map(model, vif),
    glance = map(model, glance)
  )
```

## Full Model Summary
```{r}
full_model %>%
  pull(summary) %>%
  setNames(c(
    "60s",
    "70s",
    "80s",
    "90s",
    "00s",
    "10s"
  )) %>%
  bind_rows(.id = "model") %>%
  datatable(
    extensions = "RowGroup",
    options = list(rowGroup = list(
      dataSrc = 1,
      startRender = JS(
        "function(rows, group) {",
        "  var style ='background-color:  #013220;'",
        "  var td = `<td style='${style}' colspan=12>${group}</td>`;",
        "  return $(`<tr>${td}</tr>`);",
        "}"
      )
    ))
  ) %>%
  formatRound(columns = 3:6, digits = 2)
```


## Reduced Model Summary
```{r}
reduced_model %>%
  pull(summary) %>%
  setNames(c(
    "60s",
    "70s",
    "80s",
    "90s",
    "00s",
    "10s"
  )) %>%
  bind_rows(.id = "model") %>%
  datatable(
    extensions = "RowGroup",
    options = list(rowGroup = list(
      dataSrc = 1,
      startRender = JS(
        "function(rows, group) {",
        "  var style ='background-color:  #013220;'",
        "  var td = `<td style='${style}' colspan=12>${group}</td>`;",
        "  return $(`<tr>${td}</tr>`);",
        "}"
      )
    ))
  ) %>%
  formatRound(columns = 3:6, digits = 2)
  ```

## Anova Table
```{r}
anova_tbl <- map2(full_model$model, reduced_model$model, ~ anova(.x, .y, test = "LRT")) %>%
  setNames(c(
    "60s",
    "70s",
    "80s",
    "90s",
    "00s",
    "10s"
  )) %>%
  bind_rows(.id = "model")

row.names(anova_tbl) <- NULL

anova_tbl %>%
  datatable(
    extensions = "RowGroup",
    options = list(rowGroup = list(
      dataSrc = 1,
      startRender = JS(
        "function(rows, group) {",
        "  var style ='background-color:  #013220;'",
        "  var td = `<td style='${style}' colspan=12>${group}</td>`;",
        "  return $(`<tr>${td}</tr>`);",
        "}"
      )
    ))
  ) %>%
  formatRound(columns = c(3, 5, 6), digits = 2)
```

## VIF Table
```{r}
vif_tbl <- reduced_model$vif %>%
  bind_rows() %>%
  t()

colnames(vif_tbl) <- c(
  "60s",
  "70s",
  "80s",
  "90s",
  "00s",
  "10s"
)

vif_tbl %>%
  datatable() %>%
  formatRound(columns = 1:6, digits = 2)
  ```
## Model Evaluation Table
```{r}

glance_tbl <- reduced_model$glance %>%
  bind_rows(.id = "model") %>%
  mutate(model = c(
    "60s",
    "70s",
    "80s",
    "90s",
    "00s",
    "10s"
  ))

glance_tbl %>%
  datatable() %>%
  formatRound(columns = c(2, 4, 5, 6, 7), digits = 2)
```

```{r}
scatter_lst <- map2(reduced_model$data, reduced_model$model, function(data, model) {
  data %>%
    dplyr::select(where(is.double)) %>%
    cbind(fitted = model$fitted) %>%
    pivot_longer(!fitted) %>%
    ggplot(aes(y = fitted, x = value)) +
    geom_point() +
    facet_wrap(~name, scales = "free_x")
})
```

## Evaluating Linear Assumption 

### 60s

```{r}
scatter_lst[[1]]
```

### 70s

```{r}
scatter_lst[[2]]
```

### 80s

```{r}
scatter_lst[[3]]
```

### 90s

```{r}
scatter_lst[[4]]
```

### 00s

```{r}
scatter_lst[[5]]
```

### 10s

```{r}
scatter_lst[[6]]
```

## Residual Analysis

### 60s 

```{r}
reduced_model$model[[1]] %>% autoplot(which = 1:2)
```

### 70s

```{r}
reduced_model$model[[2]] %>% autoplot(which = 1:2)
```

### 80s

```{r}
reduced_model$model[[3]] %>% autoplot(which = 1:2)
```

### 90s

```{r}
reduced_model$model[[4]] %>% autoplot(which = 1:2)
```

### 00s

```{r}
reduced_model$model[[5]] %>% autoplot(which = 1:2)
```

### 10s

```{r}
reduced_model$model[[6]] %>% autoplot(which = 1:2)
```

```{r}
plot_summs(reduced_model$model,
  model.names = c(
    "60s",
    "70s",
    "80s",
    "90s",
    "00s",
    "10s"
  )
)
```

# Conclusion

